spring.application.name=nowpick

logging.level.root = INFO
logging.level.com.nowpick = DEBUG
logging.file.name = logs/application.log

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nowpickdb?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=nowpick
spring.datasource.password=nowpick

# JPA 및 Hibernate 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# SQL 초기화 설정 (Spring Boot 2.5 부터)
spring.sql.init.mode=never

# JWT 서명에 사용되는 비밀 키
jwt.secret-key=1x9MTBsswbOln4k3kzej5dyD0ymY/ELrl0/WBK8tmFQ=
# JWT 만료 시간 (밀리초 단위)
# 1일 = 24시간 * 60분 * 60초 * 1000밀리초 = 86400000
jwt.expiration=86400000 

# 카카오맵 API KEY
kakao.rest-api-key=7a30c76a793325afc62d8f432a99f423

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG